sudo: true
os: osx
language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
install: sudo -H pip install nose xmlformatter docopt
before_script: python setup.py install
script: nosetests
