language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
install: pip install lxml docopt
before_script: python setup.py install
script: nosetests
cache:
  directories:
    - $HOME/.cache/pip